"""empty message

Revision ID: 8bc1f68820d7
Revises: 580dfaf7e3f5
Create Date: 2019-10-02 15:17:13.406188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc1f68820d7'
down_revision = '580dfaf7e3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_config', sa.Column('aquatoneAllPorts', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_config', 'aquatoneAllPorts')
    # ### end Alembic commands ###
